language: php
os: linux
services:
 - docker

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
      env: 
        - DEPS="low"
        - COMPOSER_MEMORY_LIMIT="-1"
    - php: 7.2
      env: 
        - DEPS="lock"
    - php: '7.0'
      env:
        - SYMFONY=2.8.*
    - php: '7.0'
      env:
        - SYMFONY=3.4.*
    - php: '7.1'
      env:
        - SYMFONY=4.*
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      env:
        - SYMFONY=dev-master
  allow_failures:
    - env:
        - SYMFONY=dev-master
  fast_finish: true

before_install:
  - composer self-update
  - if [ "$SYMFONY" != "" ]; then sed -ri 's/\^2.7 \|\| \^3.0 \|\| \^4.0/'$SYMFONY'/' composer.json; fi;

install:
  - if [[ $DEPS == "low" ]]; then composer update --prefer-lowest --prefer-dist --prefer-stable --no-interaction; fi
  - if [[ $DEPS == "lock" ]]; then composer install --prefer-dist --no-interaction; fi
  - if [[ -z $DEPS ]]; then composer update --prefer-dist --prefer-stable --no-interaction; fi

before_script:
  - docker-compose up -d
  - tests/wait_for_crossbar.sh

script:
  - vendor/bin/phpunit -v --coverage-clover clover.xml
  - bash <(curl -s https://codecov.io/bash) -f clover.xml
  - docker-compose logs

after_success:
  - if [[ $TEST_COVERAGE ]]; then php vendor/bin/coveralls -v; fi
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  on_success: never
  on_failure: always
