on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  tests:
    name: Test (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker compose
        run: docker-compose up -d && tests/wait_for_crossbar.sh
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=build/coverage-report.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          file: build/coverage-report.xml