on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  tests:
    name: Test (PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
            symfony: "^4.4"
            dependency-versions: "lowest"
          - php: 8.1
            symfony: "^5.4"
            dependency-versions: "highest"
          - php: 8.2
            symfony: "^5.4"
            dependency-versions: "highest"
          - php: 8.3
            symfony: "^6.4"
            dependency-versions: "highest"
          - php: 8.4
            symfony: "^6.4"
            dependency-versions: "highest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker compose
        run: docker compose up -d
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Restrict Symfony version
        if: matrix.symfony
        run: composer require "symfony/symfony:${{ matrix.symfony }}" --no-update
      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependency-versions }}
      - name: Docker compose wait
        run: docker compose up --wait crossbar
      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=build/coverage-report.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/coverage-report.xml
          fail_ci_if_error: true
